from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class StateStore(Protocol):
    def save(self, key: str, data: dict[str, Any]) -> None: ...
    def load(self, key: str) -> dict[str, Any] | None: ...
    def delete(self, key: str) -> bool: ...
    def exists(self, key: str) -> bool: ...
    def list_keys(self) -> list[str]: ...
